### ISSUE TITLE
dice sourcecode missing for Project 11

### ISSUE THREAD

**Issue by danielgohlke** [sunfounder/Sunfounder_SuperKit_Python_code_for_RaspberryPi#10]
dice.py is missing for Project 11

**Comment by sunfounder** [comment]
@danielgohlke-zanox 
Thanks for the heads up, the old one is a little shy to use, so we remove it and rewrite a new one. but forget to upload it.
Now it's uploaded. please pull the new one using 

```
git pull origin master
```

**Comment by danielgohlke** [comment]
thank you ;D
