### ISSUE TITLE
Request for Clarification about How the Python code Logic of writing 0x80 to DSI/SDI pin 11 once in Sequence of 8 Loops to Light a Different one of 8 LEDs each Time in 10_74HC595_LED.py 

### ISSUE THREAD

**Issue by rdjmsy** [sunfounder/Sunfounder_SuperKit_Python_code_for_RaspberryPi#2]
I have a question regarding the 10_74HC595_LED,py script's line 47 where it seems to write 0x80 or 128 to the DS/SDI pin on the 74HC595 chip once every eight loops through the def_hc595_in(dat) function.  

I understand that 0x80 is sent to the serial Data serial in pin on the 74HC595 chip for conversion to parallel output on the 8 pins driving the 8 LEDs, at a different position in the sequence of 0-7 (bin) for each of the eight data words in the WhichLeds list.  I just cannot quite yet comprehend how that lights a different LED each time through.  If you put in a 128, shift that with a positive transiton of SRCLCK/the SHCP pin via pin 13 on the GPIO, wouldn't that always light the second or the seventh LED over and over again instead of sequencing through lighting all eight LEDs, e.g. once every 8 loops, per data serial in word,  in of 128 total loops. per call of the def loop() function?

The code in the 10_74HC595_LED.py function/script clearly works well and succeeds  lighting each of the eight LEDs first left to right, then right to left, then repeat both over and over,   How the program logic invoked with the the loop, hc595(dat) and hc595_out() functions in the 10_74HC595_LED.py script actually achieves this is still more than a bit mysterious to me.

I am hoping that anyone who understands how this code logic actually works could find the time in their busy schedule to break this bit of the program execution logic and how it interacts with the 74HC595 chip to achieve these operational results down and reply in kind with a bit of low-level clarification and detail.

**Comment by rdjmsy** [comment]
![10_74hc595_led-dot-py](https://cloud.githubusercontent.com/assets/9126878/12027755/0381f4e0-ad89-11e5-98db-e604031bfd7a.JPG)

**Comment by rdjmsy** [comment]
![sunfounder-super-kit_4_rpi-lession-10_74hc595_8led-ckt-fritz_diag-captr-1](https://cloud.githubusercontent.com/assets/9126878/12027884/2d513b12-ad8b-11e5-9df8-819f3cda65d1.JPG)

**Comment by rdjmsy** [comment]
![sunfounder-super-kit_4_rpi-lession-10_74hc595_8led-ckt-fritz_diag-captr-1](https://cloud.githubusercontent.com/assets/9126878/12027981/06fe2c66-ad8d-11e5-89a9-e8ae8f3ad588.JPG)

**Comment by Anythingwillbeok** [comment]
Studying....

**Comment by sunfounder** [comment]
First you need to know that 0x80 does not mean 128 in decimal, but 1000 0000 in binary. And you should understand the WhichLeds list. It contains 8 values (maps) in heximal, and you should take them each an 8-bit binary number. Each bit of an individual number represents one of the 8 LEDs. For example, 0x01 is 0000 0001 in binary, indicating the first LED lights up and others stay dim. It's similar for the rest values. 
The def loop() function:
   In each for loop, it circulates the WhichLeds maps, one at each time. Then the map is sent to the 74HC595 in serial via hc595_in(), and then 74HC595 converts the serial data to parallel data to control the 8 LEDs.
